# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Magical Unicorns of Pittsburgh
email: alex.hendershott@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ultrices tristique urna et volutpat.
  Duis elementum, orci non iaculis efficitur, nisl eros mattis ipsum, sed tristique massa lorem at ligula.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://magicalunicornsofpittsburgh.com" # the base hostname & protocol for your site
twitter_username: pghunis
github_username:  pghunis

# Build settings
markdown: kramdown
