# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Magical Unicorns of Pittsburgh
email: alex.hendershott@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  MUOP is dedicated to the most in demand and rarest of product team members —
  someone with excellent interaction design skills, visual design skills, and
  coding ability. The mythical designer and developer. We create and bring
  to life. We have a passion for the design of every pixel on the screen, and a
  passion for making sure that pixel comes to life with functionality that
  excites anyone who interacts. Join MUOP and network with fellow Unicorns,
  talk about your experiences, and teach us new skills. We’re a meticulous
  bunch that never stops learning.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://magicalunicornsofpittsburgh.com" # the base hostname & protocol for your site
twitter_username: pghunicorns
instagram_username: pghunicorns
# github_username:  muop

# Sponsors
sponsor-1-url: http://www.roketco.com
sponsor-1: Roket - roketco.com

# Build settings
markdown: kramdown

# Authors
authors:
  alex:
    name: Alex Hendershott
    gravatar: 9172a7b203ea64014c2002566f493afb
    bio: > # this means to ignore newlines until "email:"
      Alex is Co-Founder and Technology Lead at <a href="http://roketco.com" target="_blank">Roket</a> — a digital agency
      fusing entrepreneurial passion and hustle to launch big ideas. We design
      and develop purpose-built websites and innovative applications for
      growing brands.

    email: alex@roketco.com
    web: http://www.roketco.com
    twitter: alexhendershott
    github: alexhendershott
    instagram: alexhendershott
    facebook: alexhendershott
